### ISSUE TITLE
Dockerfile: sonar-scanner --version fails

### ISSUE THREAD

**Issue by bartan0** [vazco/teamcity-agent-node#2]
Dockerfile specifies the last step of the build process as running some version checks. One of them is `sonar-scanner --version` - and this check fails.

Error message:

```
+ sonar-scanner --version
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Steps to reproduce:

1. Assure CWD is the root directory of this repo
2. Run `docker build -tteamcity .`

**Comment by MacRusher** [comment]
Solved by #3
